name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run clang
      shell: bash
      run: |
        cd AllBuilds
        cd clang.11.elf.c.safe_stack
        clang -Wall hellocpp.cpp -O2 -g -gdwarf-5 -o hellocpp_with_safe_stack -fsanitize=safe-stack
